import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/component/provider";
import { SessionProvider } from "next-auth/react";

const poppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} m-0 p-0 antialiased`}
        cz-shortcut-listen="true"
      >
        <SessionProvider>
          {" "}
          <Providers>
            <div className="relative h-screen">{children}</div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
