import { Geist, Geist_Mono, Poppins, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/component/provider";
import { SessionProvider } from "next-auth/react";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${poppins.variable} antialiased`}
    >
      <body className={`$ m-0 p-0 `} cz-shortcut-listen="true">
        <SessionProvider>
          <Providers>
            <div className="relative h-screen">{children}</div>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
